Feat/with-radix
Maxihost/metal-ui pull request #150
Opened 2021-02-26 21:13 UTC by esoubihe

Inroduces a few new ocmponents based on (Radix UI)[https://radix-ui.com/primitives/docs/overview/introduction] while also removing others. @n23daniel Lmk what you think of this

2021-03-12 22:06 UTC, n23daniel requested changes
Great work on this one! I've got just a question and a small change request.
Looking through the code, I got to really like the radix-ui concept - the way it offers the flexibility of styling.

2021-03-15 19:07 UTC, esoubihe commented on package.json
> +    "react-dom": "^17.0.1",
Good call!

2021-03-15 19:13 UTC, esoubihe commented on package.json
> +    "react-dom": "^17.0.1",
react and react-dom were duplicated. I've also moved all dependency packages to `devDependencies`. Does that make sense?

2021-03-15 19:21 UTC, esoubihe commented on src/DropdownMenu/index.js
> +  `,
Thanks, fixed

2021-03-15 19:22 UTC, n23daniel commented on package.json
> +    "react-dom": "^17.0.1",
yeah, we don't use `npm install` on production environment for metal-ui so it's fine to move to `devDependencies`. Looks good 👌

2021-04-02 16:47 UTC, closed without merging