Feature/GitHub action  ci
Maxihost/metal-ui pull request #94
Opened 2020-10-08 17:36 UTC by JarrodMFlesch

Hey @esoubihe here is the PR for the github actions - it took me a little bit to understand how they function, but I have a much better understanding now. So with that being said, I would love for you to give these a test and report back to me with any feedback!
<br />

CI Test will run when:
- PR or Push gets made to Develop
- PR or Push gets made to Master

CI Release will run when:
- PR or Push gets made to Master and the CI Test passes

<br />
The releases are based on Semantic Releases criteria, i.e. using **feat:** and **fix:** with your commit messages.

Let me know if you run into anything!

2020-10-13 14:51 UTC, esoubihe commented on .github/workflows/ci.yml
> +        # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
@JarrodMFlesch I think we need to uncomment this in order to be able to push it to NPM.

2020-10-13 14:51 UTC, esoubihe commented on package.json
> +  "private": true,
I believe this was left here by accident?

2020-10-13 14:52 UTC, esoubihe commented on .github/workflows/ci.yml
> +        # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
Sorry, just saw your comment. We already have `NPM_TOKEN` setup.

2020-10-13 14:58 UTC, esoubihe commented on .github/workflows/ci.yml
> +        # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
Thanks. Feel free to amend that as I'm unable to push to your PR

2020-10-22 21:08 UTC, JarrodMFlesch commented
@esoubihe and team - Does anyone know how we can fix the `package-lock.json` conflict? I had to remove node modules and reinstall to get my workflow scripts to run properly, so they are not in sync anymore. When I pull from master I don't get a conflict, so I am unable to resolve it locally, any ideas?

2020-10-27 14:18 UTC, nathanmrtns commented
> @esoubihe and team - Does anyone know how we can fix the `package-lock.json` conflict? I had to remove node modules and reinstall to get my workflow scripts to run properly, so they are not in sync anymore. When I pull from master I don't get a conflict, so I am unable to resolve it locally, any ideas?

Did you try deleting your local package-lock file, regenerating and pull from master to see if you get any conflicts?

2020-10-27 15:11 UTC, esoubihe commented
`package-lock.json` exists for a reason. We should avoid deleting it. 

It should be ok this once based on what I've seen for the current dependencies, but it's best to adjust your workflow to keep package and lock updated than it is to take the risk of unknowingly updating dependencies that could break things.

2020-10-27 15:45 UTC, JarrodMFlesch commented
@nathanmrtns I will give that a shot!

2020-10-28 15:15 UTC, JarrodMFlesch commented
@esoubihe & @nathanmrtns So I think I have gotten to the bottom of this. I believe the lock file on master is actually _out of date_, if you run `npm ci` (which is what I am running inside my ci) you will see that the lock file is out of date compared to the actual package versions in the package.json. 

Can we have this fixed on master to fix this conflict? That is the place this issue should be resolved.

2020-10-28 17:38 UTC, nathanmrtns commented
@JarrodMFlesch I will fork your repository to see if I can fix it

2020-10-28 18:04 UTC, nathanmrtns commented
Hey @JarrodMFlesch can you check if merging[ THIS PR ](https://github.com/trouble/metal-ui/pull/11)into your branch fixes the problem?

2020-10-28 18:18 UTC, JarrodMFlesch commented
@nathanmrtns yep that seemed to fix the package lock conflict 👍

2020-10-28 19:12 UTC, nathanmrtns commented
> @nathanmrtns This is used to fix an issue with invalid blobs in storybook.

I didn't know, I just wanted to change the package lock in this pr to this branch

2020-10-28 19:13 UTC, nathanmrtns requested changes

2020-10-28 19:13 UTC, nathanmrtns commented on .storybook/main.js
> +  stories: ["../src/**/*.stories.(js|mdx)"],
```suggestion
  stories: ["../src/**/*.stories.@(js|mdx)"],
```

2020-10-28 19:13 UTC, nathanmrtns commented on .storybook/main.js
> +  stories: ["../src/**/*.stories.(js|mdx)"],
Just to revert that change.

2020-10-28 20:06 UTC, JarrodMFlesch commented on .storybook/main.js
> +  stories: ["../src/**/*.stories.(js|mdx)"],
reverted here c050d8b

2020-10-28 20:27 UTC, nathanmrtns approved these changes

2020-10-31 16:13 UTC, merged